### ISSUE TITLE
关于末端的状态的输入

### ISSUE THREAD

**Issue by Wangbo-CASIA** [rise-policy/RISE#1]
请问末端实时位姿为什么不用输入到网络？

**Comment by chenxi-wang** [comment]
你好，这是因为末端位姿隐式编码在点云里的夹爪部分，通过分析夹爪的点云可以推断当前末端的状态

**Comment by Wangbo-CASIA** [comment]
感谢你的回复 还有一个问题  我使用40条实采数据训练rise模型  实际部署效果非常差 请问您这边训练时还有其他的trick吗 或者我采集真机数据时有需要注意的地方吗

**Comment by chenxi-wang** [comment]
可能出问题的地方比较多，相机内参不对会影响点云合成，外参不对会影响点云的位置，也可以检查一下workspace范围和tcp normalize范围有没有跟当前部署环境对上，要保证这两个参数和训练用的一样

你可以把训练和部署时送进网络的点云可视化出来看看对不对，也可以提供一条完整数据和相关的配置文件给我看看
