### ISSUE TITLE
关于每个epoch开始时的数据加载问题

### ISSUE THREAD

**Issue by lyxichigoichie** [rise-policy/RISE#2]
Hi，我在跑RISE训练的时候发现，在每个epoch开始时都需要耗费非常长的时间来加载数据，统计下来发现加载数据耗时竟然比训练一个epoch的耗时还要长。想问一下作者在训练的时候有没有遇到类似的问题，如果遇到的话是如何解决的。

Thanks

**Comment by chenxi-wang** [comment]
你好，训练的时候确实会有这个问题，主要原因是3D数据批量处理的效率比纯2D图像要低，代码里直接用高清图生成点云再做处理，会消耗更多资源。可以把RGB-D图像resize到原来的一半（相机内参也要同步放缩），速度会有明显提升。

相同训练参数下，处理速度因CPU性能而异，我们在 Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz 上迭代一个epoch需要1-2分钟时间，供你参考，如果差得太远可能还存在其他问题。

**Comment by lyxichigoichie** [comment]
> 你好，训练的时候确实会有这个问题，主要原因是3D数据批量处理的效率比纯2D图像要低，代码里直接用高清图生成点云再做处理，会消耗更多资源。可以把RGB-D图像resize到原来的一半（相机内参也要同步放缩），速度会有明显提升。
> 
> 相同训练参数下，处理速度因CPU性能而异，我们在 Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz 上迭代一个epoch需要1-2分钟时间，供你参考，如果差得太远可能还存在其他问题。

了解，谢谢
